// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;

using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class Beneficiary: BaseEntity
{
    public int PersonId { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public virtual ICollection<BrigadeBeneficiary> BrigadeBeneficiaries { get; set; } = new List<BrigadeBeneficiary>();

    public virtual Person Person { get; set; }
}