// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class BrigadeBeneficiary: BaseEntity<int>
{

    public int BrigadeId { get; set; }

    public int BeneficiaryId { get; set; }

    public int BeneficiaryTypeId { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }
 

    public virtual Beneficiary Beneficiary { get; set; }

    public virtual BeneficiaryType BeneficiaryType { get; set; }

    public virtual Brigade Brigade { get; set; }
}