// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class BrigadeVoluntareer: BaseEntity
{
    public int BrigadeId { get; set; }

    public int VolunteerId { get; set; }

    public string Status { get; set; }

    
    public virtual Brigade Brigade { get; set; }

    public virtual Volunteer Volunteer { get; set; }
}