// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class Brigade: BaseEntity<int>
{
 

    public int? CompanyId { get; set; }

    public int PersonId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime Start { get; set; }

    public DateTime End { get; set; }

    public string Status { get; set; }

 

    public virtual ICollection<BrigadeBeneficiary> BrigadeBeneficiaries { get; set; } = new List<BrigadeBeneficiary>();

    public virtual ICollection<BrigadeVoluntareer> BrigadeVoluntareers { get; set; } = new List<BrigadeVoluntareer>();

    public virtual Company Company { get; set; }

    public virtual ICollection<Donation> Donations { get; set; } = new List<Donation>();

    public virtual Person Person { get; set; }
}