// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;

using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class CompanyUser: BaseEntity
{
    public int UserId { get; set; }

    public int CompanyId { get; set; }

    public virtual Company Company { get; set; }

    public virtual User User { get; set; }
}