// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;

using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class Company: BaseEntity<int>
{
 

    public string Identificacion { get; set; }

    public string Nombre { get; set; }

    public string Status { get; set; }

   
    public virtual ICollection<Brigade> Brigades { get; set; } = new List<Brigade>();

    public virtual ICollection<CompanyUser> CompanyUsers { get; set; } = new List<CompanyUser>();

    public virtual ICollection<SmtpConfiguration> SmtpConfigurations { get; set; } = new List<SmtpConfiguration>();
}