// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;

using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class Donor: BaseEntity
{
    public int PersonId { get; set; }

    public string Status { get; set; } 

    public virtual ICollection<Donation> Donations { get; set; } = new List<Donation>();

    public virtual Person? Person { get; set; }
}