// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;

using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class Person: BaseEntity<int>
{


    public int? CompanyId { get; set; }

    public string FirstName { get; set; }

    public string SecondName { get; set; }

    public string LastName { get; set; }

    public string SecondLastName { get; set; }

    public string NameCompleted { get; set; }

    public string Email { get; set; }

    public short? IdentificationTypeId { get; set; }

    public string Identification { get; set; }

    public string Phone { get; set; }

    public int? UserId { get; set; }

    public bool Volunteer { get; set; }

    public bool Donor { get; set; }

    public string Status { get; set; }


    public virtual Beneficiary Beneficiary { get; set; }

    public virtual ICollection<Brigade> Brigades { get; set; } = new List<Brigade>();

    public virtual Donor? IdNavigation { get; set; } = null;

    public virtual IdentificationType IdentificationType { get; set; }

    public virtual User? User { get; set; } = null;

    public virtual Volunteer? VolunteerNavigation { get; set; } = null;
}