// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FundacionAMA.Domain.Shared.Entities;

using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Entities;

public partial class RegistrationVolunteer: BaseEntity
{
    public int VolunteerId { get; set; }

    public int? DonorId { get; set; }

    public string Name { get; set; }

    public string Lastname { get; set; }

    public string Gender { get; set; }

    public string Address { get; set; }

    public int? Telephone { get; set; }

    public string Mail { get; set; }

    public string Availability { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Activity { get; set; }

    public virtual ICollection<ConsultVolunteer> ConsultVolunteers { get; set; } = new List<ConsultVolunteer>();
}