// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Domain.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Domain.Persistence.Configurations
{
    public partial class ActivityTypeConfiguration : IEntityTypeConfiguration<ActivityType>
    {
        public void Configure(EntityTypeBuilder<ActivityType> entity)
        {
            entity.ToTable("ActivityType");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
 
            entity.Property(e => e.Name)
            .HasMaxLength(60)
            .IsFixedLength();
            entity.Property(e => e.Status)
            .IsRequired()
            .HasDefaultValueSql("(N'')");
            entity.HasData(new ActivityType
            {
                Id = 1,
                Name = "PRUEBA DE ACTIVIDAD",
                Status = "A",
                CreatedAt = DateTime.Now,
                Active = true,
            });

           OnConfigurePartial(entity);

        }

        partial void OnConfigurePartial(EntityTypeBuilder<ActivityType> entity);
    }
}
