// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class BrigadeVoluntareerConfiguration : IEntityTypeConfiguration<BrigadeVoluntareer>
    {
        public void Configure(EntityTypeBuilder<BrigadeVoluntareer> entity)
        {
            entity.HasKey(e => new { e.BrigadeId, e.VolunteerId });

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Status)
            .IsRequired()
            .HasDefaultValueSql("(N'')");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Brigade).WithMany(p => p.BrigadeVoluntareers)
            .HasForeignKey(d => d.BrigadeId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_BrigadeVoluntareers_Brigades");

            entity.HasOne(d => d.Volunteer).WithMany(p => p.BrigadeVoluntareers)
            .HasForeignKey(d => d.VolunteerId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_BrigadeVoluntareers_Volunteers");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BrigadeVoluntareer> entity);
    }
}
