// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class BrigadeBeneficiaryConfiguration : IEntityTypeConfiguration<BrigadeBeneficiary>
    {
        public void Configure(EntityTypeBuilder<BrigadeBeneficiary> entity)
        {
            entity.Property(e => e.Id).
                ValueGeneratedOnAdd();
            entity.Property(e => e.Id)
            .HasMaxLength(10)
            .IsFixedLength();
            entity.Property(e => e.Description)
            .HasMaxLength(10)
            .IsFixedLength();
            entity.Property(e => e.Status)
            .IsRequired()
            .HasDefaultValueSql("(N'')");

            entity.HasOne(d => d.Beneficiary).WithMany(p => p.BrigadeBeneficiaries)
            .HasForeignKey(d => d.BeneficiaryId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_BrigadeBeneficiaries_Beneficiaries");

            entity.HasOne(d => d.BeneficiaryType).WithMany(p => p.BrigadeBeneficiaries)
            .HasForeignKey(d => d.BeneficiaryTypeId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_BrigadeBeneficiaries_BeneficiaryType");

            entity.HasOne(d => d.Brigade).WithMany(p => p.BrigadeBeneficiaries)
            .HasForeignKey(d => d.BrigadeId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_BrigadeBeneficiaries_Brigades");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BrigadeBeneficiary> entity);
    }
}
