// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class BrigadeConfiguration : IEntityTypeConfiguration<Brigade>
    {
        public void Configure(EntityTypeBuilder<Brigade> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_Brigade");
            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Description)
            .HasMaxLength(500)
            .IsUnicode(false);
            entity.Property(e => e.End).HasColumnType("date");
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(250)
            .IsUnicode(false);
            entity.Property(e => e.Start).HasColumnType("date");
            entity.Property(e => e.Status)
            .IsRequired()
            .HasDefaultValueSql("(N'')");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Company).WithMany(p => p.Brigades)
            .HasForeignKey(d => d.CompanyId)
            .HasConstraintName("FK_Brigades_Company");

            entity.HasOne(d => d.Person).WithMany(p => p.Brigades)
            .HasForeignKey(d => d.PersonId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Brigades_Persons");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Brigade> entity);
    }
}
