// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class ConsultVolunteerConfiguration : IEntityTypeConfiguration<ConsultVolunteer>
    {
        public void Configure(EntityTypeBuilder<ConsultVolunteer> entity)
        {
            entity.HasKey(e => e.Consult).HasName("PK__ConsultV__ACEE1F39D2C73D2A");

            entity.Property(e => e.Consult).HasColumnName("consult");
            entity.Property(e => e.VolunteerId).HasColumnName("volunteer_id");

            entity.HasOne(d => d.Volunteer).WithMany(p => p.ConsultVolunteers)
            .HasForeignKey(d => d.VolunteerId)
            .HasConstraintName("FK__ConsultVo__volun__70DDC3D8");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ConsultVolunteer> entity);
    }
}
