// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class DonationConfiguration : IEntityTypeConfiguration<Donation>
    {
        public void Configure(EntityTypeBuilder<Donation> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_DONATION_ID"); // Define la clave primaria
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd(); // Indica que es autoincremental

 
            entity.Property(e => e.AssignedAt).HasColumnType("datetime");
            entity.Property(e => e.Name)
            .HasMaxLength(60)
            .IsFixedLength();
            entity.Property(e => e.Price).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Status)
            .IsRequired()
            .HasDefaultValueSql("(N'')");
            entity.Property(e => e.Total).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.Brigade).WithMany(p => p.Donations)
            .HasForeignKey(d => d.BrigadeId)
            .HasConstraintName("FK_Donations_Brigades");

            entity.HasOne(d => d.DonationType).WithMany(p => p.Donations)
            .HasForeignKey(d => d.DonationTypeId)
            .HasConstraintName("FK_Donations_DonationType");

            entity.HasOne(d => d.Person).WithMany(p => p.Donations)
            .HasForeignKey(d => d.PersonId)
            .HasConstraintName("FK_Donations_Donors");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Donation> entity);
    }
}
