// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class PersonConfiguration : IEntityTypeConfiguration<Person>
    {
        public void Configure(EntityTypeBuilder<Person> entity)
        {
 
            entity.HasKey(e => e.Id).HasName("PK_PERSON_ID");
            entity.HasIndex(e => e.Id).IsUnique();
            entity.Property(e => e.FirstName).IsRequired();
            entity.Property(e => e.Identification)
            .IsRequired()
            .HasMaxLength(22)
            .IsUnicode(false);
            entity.Property(e => e.LastName).IsRequired();
            entity.Property(e => e.NameCompleted).IsRequired();
            entity.Property(e => e.Phone)
            .HasMaxLength(10)
            .IsFixedLength();
            entity.Property(e => e.Status)
            .IsRequired()
            .HasDefaultValueSql("(N'')");
 

            entity.HasOne(d => d.IdentificationType).WithMany(p => p.People)
            .HasForeignKey(d => d.IdentificationTypeId)
            .HasConstraintName("FK_Persons_IdentificationType");

            entity.HasOne(d => d.User).WithMany(p => p.People)
            .HasForeignKey(d => d.UserId)
            .HasConstraintName("FK_Persons_Users");

            OnConfigurePartial(entity);
        }
        partial void OnConfigurePartial(EntityTypeBuilder<Person> entity);
    }
}
