// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class RegistrationVolunteerConfiguration : IEntityTypeConfiguration<RegistrationVolunteer>
    {
        public void Configure(EntityTypeBuilder<RegistrationVolunteer> entity)
        {
            entity.HasKey(e => e.VolunteerId).HasName("PK__Registra__0FE766B10C1C8324");

            entity.ToTable("RegistrationVolunteer");

            entity.Property(e => e.VolunteerId).HasColumnName("volunteer_id");
            entity.Property(e => e.Activity)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("activity");
            entity.Property(e => e.Address)
            .HasMaxLength(60)
            .IsUnicode(false)
            .HasColumnName("address");
            entity.Property(e => e.Availability)
            .HasMaxLength(60)
            .IsUnicode(false)
            .HasColumnName("availability");
            entity.Property(e => e.DonorId).HasColumnName("donor_id");
            entity.Property(e => e.EndDate)
            .HasColumnType("date")
            .HasColumnName("end_date");
            entity.Property(e => e.Gender)
            .HasMaxLength(45)
            .IsUnicode(false)
            .HasColumnName("gender");
            entity.Property(e => e.Lastname)
            .HasMaxLength(45)
            .IsUnicode(false)
            .HasColumnName("lastname");
            entity.Property(e => e.Mail)
            .HasMaxLength(45)
            .IsUnicode(false)
            .HasColumnName("mail");
            entity.Property(e => e.Name)
            .HasMaxLength(45)
            .IsUnicode(false)
            .HasColumnName("name");
            entity.Property(e => e.StartDate)
            .HasColumnType("date")
            .HasColumnName("start_date");
            entity.Property(e => e.Telephone).HasColumnName("telephone");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RegistrationVolunteer> entity);
    }
}
