// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class SmtpConfigurationConfiguration : IEntityTypeConfiguration<SmtpConfiguration>
    {
        public void Configure(EntityTypeBuilder<SmtpConfiguration> entity)
        {
            entity.Property(e => e.DisplayName).IsRequired();
            entity.Property(e => e.Host).IsRequired();
            entity.Property(e => e.Mail).IsRequired();
            entity.Property(e => e.Password).IsRequired();
            entity.Property(e => e.Status)
            .IsRequired()
            .HasDefaultValueSql("(N'')");

            entity.HasOne(d => d.Company).WithMany(p => p.SmtpConfigurations)
            .HasForeignKey(d => d.CompanyId)
            .HasConstraintName("FK_SmtpConfigurations_Company");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SmtpConfiguration> entity);
    }
}
