// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.Property(e => e.Email)
            .IsRequired()
            .HasMaxLength(150);
            entity.Property(e => e.Identification)
            .IsRequired()
            .HasMaxLength(21);
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(255);
            entity.Property(e => e.Password).IsRequired();
            entity.Property(e => e.Salt)
            .IsRequired()
            .HasDefaultValueSql("(N'')");
            entity.Property(e => e.Status)
            .IsRequired()
            .HasDefaultValueSql("(N'')");
            entity.HasData(
                 new User
                 {
                     Id = 1,
                     Identification = "9999999999999",
                     Name = "System",
                     Email = "system@email.com",
                     Password = "hx7w741jRKptsZJYyBjLQfz4agjKMGEJoK0kVwbbthI=",
                     Salt = "UhfyKxRscxd78Aoj0WOzigBOnis+fUNtHEc8kfQkOCg=",
                     Status = "A",
                     CreatedAt = DateTime.Now,
                     TempCode=Guid.NewGuid().ToString(),
                 }
             );
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<User> entity);
    }
}
