// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FundacionAMA.Domain.Entities;
using FundacionAMA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FundacionAMA.Infrastructure.Persistence.Configurations
{
    public partial class VolunteerConfiguration : IEntityTypeConfiguration<Volunteer>
    {
        public void Configure(EntityTypeBuilder<Volunteer> entity)
        {
            entity.HasKey(e => e.PersonId);

            entity.Property(e => e.PersonId).ValueGeneratedOnAdd();
            entity.Property(e => e.Address)
            .IsRequired()
            .HasMaxLength(60)
            .IsUnicode(false);
            entity.Property(e => e.EndDate).HasColumnType("date");
            entity.Property(e => e.Gender)
            .IsRequired()
            .HasMaxLength(45)
            .IsUnicode(false);
            entity.Property(e => e.StartDate).HasColumnType("date");
            entity.Property(e => e.Status)
            .IsRequired()
            .HasDefaultValueSql("(N'')");

            entity.HasOne(d => d.ActivityType).WithMany(p => p.Volunteers)
            .HasForeignKey(d => d.ActivityTypeId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Volunteers_ActivityType");

            entity.HasOne(d => d.Person).WithOne(p => p.VolunteerNavigation)
                      .IsRequired(false)

            .HasForeignKey<Volunteer>(d => d.PersonId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Volunteers_Persons");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Volunteer> entity);
    }
}
