name: AMA Docker Images

on:
  push:
    branches:
      - main 

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u gfabianmm --password-stdin

    - name: Build and Push Backend Image
      run: |
        IMAGE_TAG=$(date '+%Y%m%d%H%M%S')
        docker build -t gfabianmm/ama:backend-latest -t gfabianmm/ama:backend-$IMAGE_TAG -f src/Backend/src/FundacionAMA.API/Dockerfile .
        docker push gfabianmm/ama:backend-latest
        docker push gfabianmm/ama:backend-$IMAGE_TAG
        

    - name: Build and Push Frontend Image
      run: |
        IMAGE_TAG=$(date '+%Y%m%d%H%M%S')
        docker build -t gfabianmm/ama:frontend-latest -t gfabianmm/ama:frontend-$IMAGE_TAG -f src/Frontend/Dockerfile.frontend .
        docker push gfabianmm/ama:frontend-latest
        docker push gfabianmm/ama:frontend-$IMAGE_TAG
